#ifndef SBK_VERSION_H
#define SBK_VERSION_H

#define SBK_STRINGIFY(x)        #x
#define SBK_XSTRINGIFY(x)       SBK_STRINGIFY(x)

#define SBK_PRODUCT_NAME        "Sound Bakery"
#define SBK_VERSION_MAJOR       0
#define SBK_VERSION_MINOR       1
#define SBK_VERSION_PATCH       0
#define SBK_VERSION_COMMIT_ID   
#define SBK_VERSION_STRING      SBK_XSTRINGIFY(SBK_VERSION_MAJOR) "." SBK_XSTRINGIFY(SBK_VERSION_MINOR) "." SBK_XSTRINGIFY(SBK_VERSION_PATCH) "+" SBK_STRINGIFY(SBK_VERSION_COMMIT_ID)

#endif // SBK_VERSION_H
