var annotated_dup =
[
    [ "audio_meter_utils", null, [
      [ "audio_meter_draw_info", "structaudio__meter__utils_1_1audio__meter__draw__info.html", null ]
    ] ],
    [ "rttr", null, [
      [ "sequential_container_mapper< eastl::vector< T, Allocator > >", "structrttr_1_1sequential__container__mapper_3_01eastl_1_1vector_3_01T_00_01Allocator_01_4_01_4.html", null ],
      [ "wrapper_mapper< sbk::core::child_ptr< T > >", "structrttr_1_1wrapper__mapper_3_01sbk_1_1core_1_1child__ptr_3_01T_01_4_01_4.html", null ],
      [ "wrapper_mapper< sbk::core::database_ptr< T > >", "structrttr_1_1wrapper__mapper_3_01sbk_1_1core_1_1database__ptr_3_01T_01_4_01_4.html", null ]
    ] ],
    [ "sbk", null, [
      [ "core", null, [
        [ "serialization", null, [
          [ "boost_serializer", "classsbk_1_1core_1_1serialization_1_1boost__serializer.html", null ],
          [ "serialized_associative_container", "structsbk_1_1core_1_1serialization_1_1serialized__associative__container.html", null ],
          [ "serialized_child_class", "structsbk_1_1core_1_1serialization_1_1serialized__child__class.html", null ],
          [ "serialized_object", "structsbk_1_1core_1_1serialization_1_1serialized__object.html", null ],
          [ "serialized_object_vector", "structsbk_1_1core_1_1serialization_1_1serialized__object__vector.html", null ],
          [ "serialized_object_vector< sbk::engine::sound >", "structsbk_1_1core_1_1serialization_1_1serialized__object__vector_3_01sbk_1_1engine_1_1sound_01_4.html", null ],
          [ "serialized_sequential_container", "structsbk_1_1core_1_1serialization_1_1serialized__sequential__container.html", null ],
          [ "serialized_sound", "structsbk_1_1core_1_1serialization_1_1serialized__sound.html", null ],
          [ "serialized_soundbank", "structsbk_1_1core_1_1serialization_1_1serialized__soundbank.html", null ],
          [ "serialized_standalone_object", "structsbk_1_1core_1_1serialization_1_1serialized__standalone__object.html", null ],
          [ "serialized_system", "structsbk_1_1core_1_1serialization_1_1serialized__system.html", null ],
          [ "serialized_type", "structsbk_1_1core_1_1serialization_1_1serialized__type.html", null ],
          [ "serialized_version", "structsbk_1_1core_1_1serialization_1_1serialized__version.html", null ]
        ] ],
        [ "child_ptr", "classsbk_1_1core_1_1child__ptr.html", "classsbk_1_1core_1_1child__ptr" ],
        [ "database", "classsbk_1_1core_1_1database.html", "classsbk_1_1core_1_1database" ],
        [ "database_name", "structsbk_1_1core_1_1database__name.html", null ],
        [ "database_name_comparator", "structsbk_1_1core_1_1database__name__comparator.html", null ],
        [ "database_object", "classsbk_1_1core_1_1database__object.html", null ],
        [ "database_ptr", "classsbk_1_1core_1_1database__ptr.html", "classsbk_1_1core_1_1database__ptr" ],
        [ "name", "classsbk_1_1core_1_1name.html", null ],
        [ "object", "classsbk_1_1core_1_1object.html", "classsbk_1_1core_1_1object" ],
        [ "object_owner", "classsbk_1_1core_1_1object__owner.html", "classsbk_1_1core_1_1object__owner" ],
        [ "object_ptr_comparator", "structsbk_1_1core_1_1object__ptr__comparator.html", null ],
        [ "object_tracker", "classsbk_1_1core_1_1object__tracker.html", null ],
        [ "parsed_database_name", "structsbk_1_1core_1_1parsed__database__name.html", null ],
        [ "property", "classsbk_1_1core_1_1property.html", "classsbk_1_1core_1_1property" ],
        [ "scoped_thread_domain", "classsbk_1_1core_1_1scoped__thread__domain.html", null ]
      ] ],
      [ "editor", null, [
        [ "project", "classsbk_1_1editor_1_1project.html", null ],
        [ "project_configuration", "structsbk_1_1editor_1_1project__configuration.html", "structsbk_1_1editor_1_1project__configuration" ]
      ] ],
      [ "engine", null, [
        [ "profiling", null, [
          [ "voice_tracker", "classsbk_1_1engine_1_1profiling_1_1voice__tracker.html", null ]
        ] ],
        [ "action", "structsbk_1_1engine_1_1action.html", null ],
        [ "aux_bus", "classsbk_1_1engine_1_1aux__bus.html", null ],
        [ "blend_container", "classsbk_1_1engine_1_1blend__container.html", "classsbk_1_1engine_1_1blend__container" ],
        [ "bus", "classsbk_1_1engine_1_1bus.html", null ],
        [ "container", "classsbk_1_1engine_1_1container.html", "classsbk_1_1engine_1_1container" ],
        [ "container_instance", "structsbk_1_1engine_1_1container__instance.html", null ],
        [ "effect_description", "classsbk_1_1engine_1_1effect__description.html", "classsbk_1_1engine_1_1effect__description" ],
        [ "effect_parameter_description", "classsbk_1_1engine_1_1effect__parameter__description.html", null ],
        [ "encoding_sound", "structsbk_1_1engine_1_1encoding__sound.html", null ],
        [ "event", "classsbk_1_1engine_1_1event.html", null ],
        [ "float_parameter", "classsbk_1_1engine_1_1float__parameter.html", null ],
        [ "game_object", "classsbk_1_1engine_1_1game__object.html", "classsbk_1_1engine_1_1game__object" ],
        [ "gather_children_context", "structsbk_1_1engine_1_1gather__children__context.html", "structsbk_1_1engine_1_1gather__children__context" ],
        [ "global_parameter_list", "structsbk_1_1engine_1_1global__parameter__list.html", null ],
        [ "int_parameter", "classsbk_1_1engine_1_1int__parameter.html", null ],
        [ "local_parameter_list", "structsbk_1_1engine_1_1local__parameter__list.html", null ],
        [ "named_parameter", "classsbk_1_1engine_1_1named__parameter.html", "classsbk_1_1engine_1_1named__parameter" ],
        [ "named_parameter_value", "classsbk_1_1engine_1_1named__parameter__value.html", null ],
        [ "node", "classsbk_1_1engine_1_1node.html", null ],
        [ "parameter", "classsbk_1_1engine_1_1parameter.html", "classsbk_1_1engine_1_1parameter" ],
        [ "property_subscription", "structsbk_1_1engine_1_1property__subscription.html", null ],
        [ "random_container", "classsbk_1_1engine_1_1random__container.html", "classsbk_1_1engine_1_1random__container" ],
        [ "runtime", "classsbk_1_1engine_1_1runtime.html", null ],
        [ "sequence_container", "classsbk_1_1engine_1_1sequence__container.html", "classsbk_1_1engine_1_1sequence__container" ],
        [ "sound", "classsbk_1_1engine_1_1sound.html", "classsbk_1_1engine_1_1sound" ],
        [ "sound_container", "classsbk_1_1engine_1_1sound__container.html", "classsbk_1_1engine_1_1sound__container" ],
        [ "soundbank", "classsbk_1_1engine_1_1soundbank.html", null ],
        [ "soundbank_database", "structsbk_1_1engine_1_1soundbank__database.html", null ],
        [ "soundbank_database_entry", "structsbk_1_1engine_1_1soundbank__database__entry.html", null ],
        [ "soundbank_dependencies", "structsbk_1_1engine_1_1soundbank__dependencies.html", null ],
        [ "switch_container", "classsbk_1_1engine_1_1switch__container.html", "classsbk_1_1engine_1_1switch__container" ],
        [ "system", "classsbk_1_1engine_1_1system.html", "classsbk_1_1engine_1_1system" ],
        [ "voice", "classsbk_1_1engine_1_1voice.html", "classsbk_1_1engine_1_1voice" ],
        [ "voice_dsp_instance", "structsbk_1_1engine_1_1voice__dsp__instance.html", null ],
        [ "voice_property_watch", "structsbk_1_1engine_1_1voice__property__watch.html", null ],
        [ "void_deleter", "structsbk_1_1engine_1_1void__deleter.html", null ]
      ] ],
      [ "memory", null, [
        [ "memory_resource", "classsbk_1_1memory_1_1memory__resource.html", null ],
        [ "monotonic_buffer_resource", "classsbk_1_1memory_1_1monotonic__buffer__resource.html", "classsbk_1_1memory_1_1monotonic__buffer__resource" ],
        [ "object_deleter", "structsbk_1_1memory_1_1object__deleter.html", null ],
        [ "owned_object_deleter", "structsbk_1_1memory_1_1owned__object__deleter.html", null ],
        [ "polymorphic_allocator", "classsbk_1_1memory_1_1polymorphic__allocator.html", null ],
        [ "rpmalloc_resource", "classsbk_1_1memory_1_1rpmalloc__resource.html", null ]
      ] ],
      [ "reflection", null, [
        [ "CreatePointerConversion", "structsbk_1_1reflection_1_1CreatePointerConversion.html", null ],
        [ "CreatePointerConversion< DerivedClass >", "structsbk_1_1reflection_1_1CreatePointerConversion_3_01DerivedClass_01_4.html", null ],
        [ "CreatePointerConversion< DerivedClass, BaseClass, U... >", "structsbk_1_1reflection_1_1CreatePointerConversion_3_01DerivedClass_00_01BaseClass_00_01U_8_8_8_01_4.html", null ],
        [ "CreatePointerConversion< DerivedClass, rttr::type_list< BaseClassList... > >", "structsbk_1_1reflection_1_1CreatePointerConversion_3_01DerivedClass_00_01rttr_1_1type__list_3_01BaseClassList_8_8_8_01_4_01_4.html", null ],
        [ "RegisterPointerConversionsForBaseClasses", "structsbk_1_1reflection_1_1RegisterPointerConversionsForBaseClasses.html", null ]
      ] ],
      [ "util", null, [
        [ "type_comparator", "structsbk_1_1util_1_1type__comparator.html", null ],
        [ "type_helper", "classsbk_1_1util_1_1type__helper.html", null ]
      ] ],
      [ "command_queue", "classsbk_1_1command__queue.html", null ],
      [ "detached_task", "structsbk_1_1detached__task.html", "structsbk_1_1detached__task" ],
      [ "end_of_frame_message", "structsbk_1_1end__of__frame__message.html", null ],
      [ "error", "classsbk_1_1error.html", null ],
      [ "executor", "classsbk_1_1executor.html", "classsbk_1_1executor" ],
      [ "fiber_promise", "structsbk_1_1fiber__promise.html", null ],
      [ "final_awaiter", "structsbk_1_1final__awaiter.html", null ],
      [ "load_soundbank_message", "structsbk_1_1load__soundbank__message.html", null ],
      [ "manual_executor", "classsbk_1_1manual__executor.html", "classsbk_1_1manual__executor" ],
      [ "message_queue", "classsbk_1_1message__queue.html", "classsbk_1_1message__queue" ],
      [ "mpsc_ring_buffer", "classsbk_1_1mpsc__ring__buffer.html", "classsbk_1_1mpsc__ring__buffer" ],
      [ "numeric_type", "structsbk_1_1numeric__type.html", null ],
      [ "numeric_type< T >", "structsbk_1_1numeric__type_3_01T_01_4.html", null ],
      [ "play_container_message", "structsbk_1_1play__container__message.html", null ],
      [ "post_event_message", "structsbk_1_1post__event__message.html", null ],
      [ "post_event_name_message", "structsbk_1_1post__event__name__message.html", null ],
      [ "promise_base", "classsbk_1_1promise__base.html", null ],
      [ "ready_result_awaiter", "structsbk_1_1ready__result__awaiter.html", null ],
      [ "stop_all_message", "structsbk_1_1stop__all__message.html", null ],
      [ "system_thread", "classsbk_1_1system__thread.html", null ],
      [ "task", "classsbk_1_1task.html", "classsbk_1_1task" ],
      [ "task_promise", "structsbk_1_1task__promise.html", null ],
      [ "task_promise< void >", "structsbk_1_1task__promise_3_01void_01_4.html", null ],
      [ "thread_executor", "classsbk_1_1thread__executor.html", "classsbk_1_1thread__executor" ],
      [ "unique_coroutine", "classsbk_1_1unique__coroutine.html", null ],
      [ "work_item", "classsbk_1_1work__item.html", null ]
    ] ],
    [ "add_effect_button", "classadd__effect__button.html", null ],
    [ "app_manager", "classapp__manager.html", null ],
    [ "audio_display_widget", "classaudio__display__widget.html", null ],
    [ "audio_meter_widget", "classaudio__meter__widget.html", null ],
    [ "database_widget", "classdatabase__widget.html", null ],
    [ "details_widget", "classdetails__widget.html", null ],
    [ "editor_app", "classeditor__app.html", null ],
    [ "file_browser_widget", "classfile__browser__widget.html", null ],
    [ "log_widget", "classlog__widget.html", null ],
    [ "method_drawer", "classmethod__drawer.html", null ],
    [ "new_project_widget", "classnew__project__widget.html", null ],
    [ "playable_selection", "structplayable__selection.html", null ],
    [ "player_widget", "classplayer__widget.html", null ],
    [ "project_explorer_widget", "classproject__explorer__widget.html", null ],
    [ "project_manager", "classproject__manager.html", null ],
    [ "project_nodes_widget", "classproject__nodes__widget.html", null ],
    [ "property_drawer", "classproperty__drawer.html", null ],
    [ "root_widget", "classroot__widget.html", null ],
    [ "sbk_system_config", "structsbk__system__config.html", null ],
    [ "sc_audio_chunk", "structsc__audio__chunk.html", null ],
    [ "sc_bank", "structsc__bank.html", null ],
    [ "sc_clap", "structsc__clap.html", null ],
    [ "sc_clap_node", "structsc__clap__node.html", null ],
    [ "sc_delay", "structsc__delay.html", null ],
    [ "sc_delay_config", "structsc__delay__config.html", null ],
    [ "sc_delay_node", "structsc__delay__node.html", null ],
    [ "sc_delay_node_config", "structsc__delay__node__config.html", null ],
    [ "sc_dsp", "structsc__dsp.html", null ],
    [ "sc_dsp_config", "structsc__dsp__config.html", null ],
    [ "sc_dsp_description", "structsc__dsp__description.html", null ],
    [ "sc_dsp_parameter", "structsc__dsp__parameter.html", null ],
    [ "sc_dsp_parameter_float", "structsc__dsp__parameter__float.html", null ],
    [ "sc_dsp_parameter_int", "structsc__dsp__parameter__int.html", null ],
    [ "sc_encoder", "structsc__encoder.html", null ],
    [ "sc_encoder_config", "structsc__encoder__config.html", null ],
    [ "sc_encoder_vorbis", "structsc__encoder__vorbis.html", null ],
    [ "sc_meter", "structsc__meter.html", null ],
    [ "sc_meter_node", "structsc__meter__node.html", null ],
    [ "sc_node_group", "structsc__node__group.html", null ],
    [ "SC_NODE_GROUP_DELETER", "structSC__NODE__GROUP__DELETER.html", null ],
    [ "sc_real_voice", "structsc__real__voice.html", null ],
    [ "sc_real_voice_config", "structsc__real__voice__config.html", null ],
    [ "sc_real_voice_heap_layout", "structsc__real__voice__heap__layout.html", null ],
    [ "sc_riff_chunk", "structsc__riff__chunk.html", null ],
    [ "sc_sound", "structsc__sound.html", null ],
    [ "sc_sound_config", "structsc__sound__config.html", null ],
    [ "SC_SOUND_DELETER", "structSC__SOUND__DELETER.html", null ],
    [ "sc_system", "structsc__system.html", null ],
    [ "sc_system_config", "structsc__system__config.html", null ],
    [ "sc_virtual_voice_candidate", "structsc__virtual__voice__candidate.html", null ],
    [ "sc_voice", "structsc__voice.html", null ],
    [ "selection", "structselection.html", null ],
    [ "splash_widget", "classsplash__widget.html", null ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", null ]
];