macro(setup_clang_format)
    if (${SOUND_BAKERY_FORMAT_SOURCE})
        find_program(SOUND_BAKERY_CLANG_FORMAT_EXE NAMES clang-format)
    endif()

    if(SOUND_BAKERY_CLANG_FORMAT_EXE)
        message(STATUS "Found clang-format exe")
    endif()
endmacro()

macro(setup_clang_tidy)
    if(SOUND_BAKERY_TIDY_SOURCE)
        set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
        find_program(SOUND_BAKERY_CLANG_TIDY_EXE NAMES clang-tidy)

        if(SOUND_BAKERY_CLANG_TIDY_EXE)
            message(STATUS "Found clang-tidy exe")
        else()
            message(FATAL_ERROR "Could not find clang-tidy exe")
        endif()
    endif()
endmacro()
