if(SOUND_BAKERY_DOCS)
    find_package(Doxygen)
    if(Doxygen_FOUND)
        add_subdirectory(docs)
    else()
        message(WARNING "Doxygen not found, not building docs")
    endif()
else()
    message(STATUS "Skipping docs")
endif()